# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'docker-service-connection'
  imageRepository: 'pdesaidocker/easy-kart-api-products'
  containerRegistry: 'pdesaidocker'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: BuildAndPush
      displayName: Build and Push Docker Image
      steps:
      - task: NuGetAuthenticate@1
        inputs:
          feedUrl: 'https://pkgs.dev.azure.com/pdesaiprogramming/d176b6b0-e072-4552-8c5d-e9ab3732a6df/_packaging/easy-kart/nuget/v3/index.json'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: 'EasyKart.Products/EasyKart.Products.csproj'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'EasyKart.Products/EasyKart.Products.csproj'
          arguments: '--configuration Release'
      - task: Docker@2
        displayName: Build and push Docker image
        inputs:
          command: 'buildAndPush'
          repository: $(imageRepository)
          dockerfile: 'EasyKart.Products/Dockerfile'
          buildContext: '.'
          tags: $(tag)
          containerRegistry: $(dockerRegistryServiceConnection)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    displayName: Deploy to AKS
    steps:
    - script: |
        echo "Replacing {{imageTag}} in deployment.yaml with $(tag)"
        sed -i 's/{{imageTag}}/$(tag)/g' EasyKart.Products/deployment.yaml
      displayName: Replace tag in deployment.yaml
    - task: Kubernetes@1
      displayName: Apply deployment.yaml
      inputs:
        kubernetesServiceEndpoint: 'aks-service-conn'
        namespace: 'easy-kart'
        command: 'apply'
        arguments: '-f EasyKart.Products/deployment.yaml'
    - task: Kubernetes@1
      displayName: Apply service.yaml
      inputs:
        kubernetesServiceEndpoint: 'aks-service-conn'
        namespace: 'easy-kart'
        command: 'apply'
        arguments: '-f EasyKart.Products/services.yaml'
